import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const envPath = path.join(rootDir, '.env');
const outPath = path.join(rootDir, 'env.js');

function parseEnv(content) {
  const parsed = {};

  content.split(/\r?\n/).forEach((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      return;
    }

    const equalIndex = trimmed.indexOf('=');
    if (equalIndex === -1) {
      return;
    }

    const key = trimmed.slice(0, equalIndex).trim();
    let value = trimmed.slice(equalIndex + 1).trim();

    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    parsed[key] = value;
  });

  return parsed;
}

if (!fs.existsSync(envPath)) {
  console.error('Missing .env file. Copy .env.example to .env and populate values first.');
  process.exit(1);
}

const env = parseEnv(fs.readFileSync(envPath, 'utf8'));
const required = ['FIREBASE_PROJECT_ID', 'FIREBASE_WEB_API_KEY'];
const missing = required.filter((key) => !env[key]);

if (missing.length > 0) {
  console.error(`Missing required env variables: ${missing.join(', ')}`);
  process.exit(1);
}

const output = `/**\n * Auto-generated by scripts/generate-env.mjs\n * Do not commit this file with real credentials.\n */\n(function() {\n  'use strict';\n\n  globalThis.AIO_ENV = Object.freeze(${JSON.stringify({
  FIREBASE_PROJECT_ID: env.FIREBASE_PROJECT_ID || '',
  FIREBASE_WEB_API_KEY: env.FIREBASE_WEB_API_KEY || '',
  FIREBASE_REGION: env.FIREBASE_REGION || 'us-central1',
  CLASSIFY_FUNCTION_NAME: env.CLASSIFY_FUNCTION_NAME || 'classifyTopic',
  DASHBOARD_URL: env.DASHBOARD_URL || ''
}, null, 2)});\n})();\n`;

fs.writeFileSync(outPath, output, 'utf8');
console.log(`Generated ${path.relative(rootDir, outPath)} from .env`);
